version: '2'

services:

  certs:
    build: cert-generator
    volumes:
      - x509:/x509

  cloud1.example.com:
    image: kaazing/enterprise-gateway:5.7.2
    environment:
      GATEWAY_OPTS: "-Dcloud-node-hostname=cloud1.example.com -Dcom.kaazing.kwic.logging=on"
    volumes:
      - ./config/cloud-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
      - ./config/log4j-config.xml:/kaazing-gateway/conf/log4j-config.xml:ro
      - ./utils/wait-for-files.sh:/wait-for-files.sh:ro
      - x509:/x509:ro
    ports:
      - "5551:5551"
    networks:
      kwic-net:
        aliases:
         - example.com
    command: bash -c "/wait-for-files.sh
                         /x509/stores/keystore-cloud.jceks
                         /x509/stores/keystore-cloud.pw
                         /x509/stores/truststore-cloud.jceks
                         /x509/stores/truststore-cloud.pw
                      && sleep 1
                      && gateway.start"

  cloud2.example.com:
    image: kaazing/enterprise-gateway:5.7.2
    environment:
      GATEWAY_OPTS: "-Dcloud-node-hostname=cloud2.example.com -Dcom.kaazing.kwic.logging=on"
    volumes:
      - ./config/cloud-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
      - ./config/log4j-config.xml:/kaazing-gateway/conf/log4j-config.xml:ro
      - ./utils/wait-for-files.sh:/wait-for-files.sh:ro
      - x509:/x509:ro
    ports:
      - "5552:5551"
    networks:
      kwic-net:
        aliases:
         - example.com
    command: bash -c "/wait-for-files.sh
                         /x509/stores/keystore-cloud.jceks
                         /x509/stores/keystore-cloud.pw
                         /x509/stores/truststore-cloud.jceks
                         /x509/stores/truststore-cloud.pw
                      && sleep 1
                      && gateway.start"

  onprem1.example.org:
    image: kaazing/enterprise-gateway:5.7.2
    environment:
      GATEWAY_OPTS: "-Dcom.kaazing.kwic.logging=on"
    volumes:
      - ./config/onprem-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
      - ./config/log4j-config.xml:/kaazing-gateway/conf/log4j-config.xml:ro
      - ./utils/wait-for-files.sh:/wait-for-files.sh:ro
      - x509:/x509:ro
    ports:
      - "6661:6661"
    networks:
      kwic-net:
    command: bash -c "/wait-for-files.sh
                         /x509/stores/keystore-onprem.jceks
                         /x509/stores/keystore-onprem.pw
                         /x509/stores/truststore-onprem.jceks
                         /x509/stores/truststore-onprem.pw
                      && sleep 1
                      && gateway.start"

  onprem2.example.org:
    image: kaazing/enterprise-gateway:5.7.2
    environment:
      GATEWAY_OPTS: "-Dcom.kaazing.kwic.logging=on"
    volumes:
      - ./config/onprem-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
      - ./config/log4j-config.xml:/kaazing-gateway/conf/log4j-config.xml:ro
      - ./utils/wait-for-files.sh:/wait-for-files.sh:ro
      - x509:/x509:ro
    ports:
      - "6662:6661"
    networks:
      kwic-net:
    command: bash -c "/wait-for-files.sh
                         /x509/stores/keystore-onprem.jceks
                         /x509/stores/keystore-onprem.pw
                         /x509/stores/truststore-onprem.jceks
                         /x509/stores/truststore-onprem.pw
                      && sleep 1
                      && gateway.start"

  server-a:
    image: kaazing/enterprise-gateway:5.7.2
    environment:
      GATEWAY_OPTS: "-Dservice-hostname=server-a -Dservice-port=5551"
    volumes:
      - ./config/echo-server-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
    networks:
      kwic-net:

  server-b:
    image: kaazing/enterprise-gateway:5.7.2
    environment:
      GATEWAY_OPTS: "-Dservice-hostname=server-b -Dservice-port=6661"
    volumes:
      - ./config/echo-server-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
    networks:
      kwic-net:

volumes:
  x509:

networks:
  kwic-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.35.0.0/16
          gateway: 172.35.0.1
